[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = ['@contracts=contracts/', "@diamonds/=contracts/diamond"]

[rpc_endpoints]
optimism_goerli = "${OPTIMISM_GOERLI_RPC}"

[etherscan]
optimism_goerli = { key = "${ETHERSCAN_API_KEY}", url = "${OPTIMISM_GOERLI_ETHERSCAN_URL}" }
